# Generated by Django 2.1 on 2021-02-21 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 22, 5, 16, 80439)),
        ),
    ]
